set(SUPEROPT_PROJECT_DIR "${LLVM_BINARY_DIR}/../..")
set(SUPEROPT_DIR "${SUPEROPT_PROJECT_DIR}/superopt")
set(THIRD_PARTY_DIR "${SUPEROPT_DIR}/build/third_party")

list(APPEND CMAKE_MODULE_PATH "${SUPEROPT_DIR}/cmake")
include(Base)
include(CompileFlags)

string(TOUPPER "${ARCH_SRC}" ARCH_SRC_S)
string(TOUPPER "${ARCH_DST}" ARCH_DST_S)
set(SUPEROPT_RELEVANT_ABUILD "${ARCH_SRC}_${ARCH_DST}")
set(DEFINES "-DARCH_SRC=ARCH_${ARCH_SRC_S} -DARCH_DST=ARCH_${ARCH_DST_S} -DSRC_DST=\\\"${SUPEROPT_RELEVANT_ABUILD}\\\" -DSUPEROPT_DIR=\"\\\"${SUPEROPT_DIR}\\\"\" -DENABLE_MAKE_SHARED")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${DEBUG_FLAGS} ${OPT_LEVEL} ${DEFINES}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${DEBUG_FLAGS} ${OPT_LEVEL} ${DEFINES}")
set(EQ_BINARY_DIR ${SUPEROPT_DIR}/build/${SUPEROPT_RELEVANT_ABUILD})

link_directories(${z3_lib})
link_directories(${binutils_install_dir}/lib)

INCLUDE_DIRECTORIES(${SUPEROPT_DIR}/include)
INCLUDE_DIRECTORIES(${SUPEROPT_DIR}/lib)
INCLUDE_DIRECTORIES(${SUPEROPT_DIR}/lib/eq)
INCLUDE_DIRECTORIES(${SUPEROPT_DIR}/lib/expr)
INCLUDE_DIRECTORIES(${SUPEROPT_DIR}/lib/support)
INCLUDE_DIRECTORIES(${EQ_BINARY_DIR})
INCLUDE_DIRECTORIES(${z3_include_dir})
INCLUDE_DIRECTORIES(${immer_include_dir})

list(APPEND CMAKE_BUILD_RPATH ${EQ_BINARY_DIR})
list(APPEND CMAKE_INSTALL_RPATH ${EQ_BINARY_DIR})

macro(add_superopt_shared_lib libname)
  if (NOT TARGET ${libname})
    add_library(${libname} SHARED IMPORTED GLOBAL)
    set_target_properties(${libname} PROPERTIES IMPORTED_LOCATION ${EQ_BINARY_DIR}/lib${libname}.so)
  endif()
  list(APPEND SUPEROPT_LIBS ${libname})
  #message(STATUS "SUPEROPT_LIBS=${SUPEROPT_LIBS}")
endmacro()

macro(add_superopt_static_lib libname)
  if (NOT TARGET ${libname})
    add_library(${libname} SHARED IMPORTED GLOBAL)
    set_target_properties(${libname} PROPERTIES IMPORTED_LOCATION ${EQ_BINARY_DIR}/lib${libname}.a)
  endif()
  list(APPEND SUPEROPT_LIBS ${libname})
  #message(STATUS "SUPEROPT_LIBS=${SUPEROPT_LIBS}")
endmacro()

macro(add_superopt_libs ret)
  add_superopt_shared_lib(superopt)
  add_superopt_shared_lib(eqchecker)
  add_superopt_shared_lib(sym_exec)
  add_superopt_shared_lib(rewrite_lib)
  add_superopt_shared_lib(insn)
  add_superopt_shared_lib(ptfg)
  add_superopt_shared_lib(tfg)
  add_superopt_shared_lib(graph)
  add_superopt_shared_lib(gsupport)
  add_superopt_shared_lib(exec)
  add_superopt_shared_lib(prove_lib)
  add_superopt_shared_lib(parser)
  add_superopt_shared_lib(expr)
  add_superopt_shared_lib(valtag)
  add_superopt_shared_lib(support)
  add_superopt_shared_lib(cutils)
  add_superopt_shared_lib(fpu)
  add_superopt_static_lib(gas)
  set(SUPEROPT_THIRD_PARTY_LIBS z3 ${libjemalloc_file} -lgmp -lgmpxx ${Boost_LIBRARIES} -ldl ${binutils_libs} -lm -lz -lmagic -lssl -lcrypto -lyaml-cpp -lpthread -ltirpc)
  set(${ret} ${SUPEROPT_LIBS} ${SUPEROPT_THIRD_PARTY_LIBS})
endmacro()
