find_package(Boost REQUIRED COMPONENTS system iostreams serialization filesystem)
find_package(yaml-cpp REQUIRED)
find_program(GIT git)

#set(ARCH_SRC "etfg" CACHE STRING)
#set(ARCH_DST "x64" CACHE STRING)

set(PROFILE_FLAG "")
set(DEBUG_FLAG "-g")
set(OPT "-O3")
set(SUPEROPT_DIR "${LLVM_BINARY_DIR}/../../superopt")
string(TOUPPER "${ARCH_SRC}" ARCH_SRC_S)
string(TOUPPER "${ARCH_DST}" ARCH_DST_S)
set(SUPEROPT_RELEVANT_ABUILD "${ARCH_SRC}_${ARCH_DST}")
set(DEFINES "-DARCH_SRC=ARCH_${ARCH_SRC_S} -DARCH_DST=ARCH_${ARCH_DST_S} -DSRC_DST=\\\"${SUPEROPT_RELEVANT_ABUILD}\\\" -DSUPEROPT_DIR=\"\\\"${SUPEROPT_DIR}\\\"\" -DENABLE_MAKE_SHARED")
set(EQ_BINARY_DIR ${SUPEROPT_DIR}/build/${SUPEROPT_RELEVANT_ABUILD})
set(third_party_dir "${SUPEROPT_DIR}/build/third_party")
#message(STATUS "eqchecker cmake_c_flags = ${CMAKE_C_FLAGS}")
#message(STATUS "eqchecker cmake_cxx_flags = ${CMAKE_CXX_FLAGS}")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${DEBUG_FLAG} ${PROFILE_FLAG} ${OPT} ${DEFINES}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${DEBUG_FLAG} ${PROFILE_FLAG} ${OPT} ${DEFINES}")

set(binutils_ver binutils-2.21)
set(binutils_dir ${third_party_dir}/${binutils_ver})
set(binutils_install_dir ${binutils_dir}-install)
set(binutils_lib ${binutils_install_dir}/lib/libbfd.a ${binutils_install_dir}/lib/libiberty.a)

set(z3_ver z3-4.8.14)
set(z3_dir ${third_party_dir}/z3)
set(z3_pkgname ${z3_ver}-x64-glibc-2.31)
set(z3_binpath ${z3_dir}/${z3_pkgname})
#set(z3_include ${z3_binpath}/include)
set(z3_lib ${z3_binpath}/bin)
link_directories(${z3_lib})
link_directories(${binutils_install_dir}/lib)

INCLUDE_DIRECTORIES(${SUPEROPT_DIR}/include)
INCLUDE_DIRECTORIES(${SUPEROPT_DIR}/lib)
INCLUDE_DIRECTORIES(${SUPEROPT_DIR}/lib/eq)
INCLUDE_DIRECTORIES(${SUPEROPT_DIR}/lib/expr)
INCLUDE_DIRECTORIES(${SUPEROPT_DIR}/lib/support)
INCLUDE_DIRECTORIES(${EQ_BINARY_DIR})

list(APPEND CMAKE_BUILD_RPATH ${EQ_BINARY_DIR})
list(APPEND CMAKE_INSTALL_RPATH ${EQ_BINARY_DIR})

macro(add_superopt_shared_lib libname)
  if (NOT TARGET ${libname})
    add_library(${libname} SHARED IMPORTED GLOBAL)
    set_target_properties(${libname} PROPERTIES IMPORTED_LOCATION ${EQ_BINARY_DIR}/lib${libname}.so)
  endif()
  list(APPEND SUPEROPT_LIBS ${libname})
  #message(STATUS "SUPEROPT_LIBS=${SUPEROPT_LIBS}")
endmacro()

macro(add_superopt_static_lib libname)
  if (NOT TARGET ${libname})
    add_library(${libname} SHARED IMPORTED GLOBAL)
    set_target_properties(${libname} PROPERTIES IMPORTED_LOCATION ${EQ_BINARY_DIR}/lib${libname}.a)
  endif()
  list(APPEND SUPEROPT_LIBS ${libname})
  #message(STATUS "SUPEROPT_LIBS=${SUPEROPT_LIBS}")
endmacro()

set(jemalloc_ver jemalloc)
set(jemalloc_dir ${third_party_dir}/${jemalloc_ver})
set(jemalloc_install_dir ${third_party_dir}/${jemalloc_ver}-install)
set(libjemalloc_file ${jemalloc_install_dir}/lib/libjemalloc.so)

macro(add_superopt_libs ret)
  add_superopt_shared_lib(superopt)
  add_superopt_shared_lib(eqchecker)
  add_superopt_shared_lib(sym_exec)
  add_superopt_shared_lib(rewrite_lib)
  add_superopt_shared_lib(insn)
  add_superopt_shared_lib(ptfg)
  add_superopt_shared_lib(tfg)
  add_superopt_shared_lib(graph)
  add_superopt_shared_lib(gsupport)
  add_superopt_shared_lib(exec)
  add_superopt_shared_lib(prove_lib)
  add_superopt_shared_lib(parser)
  add_superopt_shared_lib(expr)
  add_superopt_shared_lib(valtag)
  add_superopt_shared_lib(support)
  add_superopt_shared_lib(cutils)
  add_superopt_shared_lib(fpu)
  add_superopt_static_lib(fbgen)
  add_superopt_static_lib(gas)
  set(SUPEROPT_THIRD_PARTY_LIBS z3 ${libjemalloc_file} -lgmp -lgmpxx ${Boost_LIBRARIES} -ldl ${binutils_lib} -lm -lz -lmagic -lssl -lcrypto -lyaml-cpp -lpthread -ltirpc)
  set(${ret} ${SUPEROPT_LIBS} ${SUPEROPT_THIRD_PARTY_LIBS})
endmacro()
